### ISSUE TITLE
Google Retriever: AttributeError: 'list' object has no attribute 'strip'

### ISSUE THREAD

**Issue by richardhj** [amazon-science/RefChecker#21]
Got an error
```
File [~/RefChecker/refchecker/retriever/google_retriever.py:65](https://jupyter-cloud.gwdg.de/jhub/user/0712054/lab/tree/RefChecker/refchecker/retriever/google_retriever.py#line=64), in GoogleRetriever._get_queries(self, paragraph)
     61 if query is None:
     62     raise RuntimeError(
     63         "Retriever: Empty response from LLM for query generation."
     64     )
---> 65 return [query.strip()]

AttributeError: 'list' object has no attribute 'strip'
```

https://github.com/amazon-science/RefChecker/blob/0dfe67fe3e4f83413e747799461bab046ac2f5b4/refchecker/retriever/google_retriever.py#L65

The return value of `query` is expected to be a list indeed: https://github.com/amazon-science/RefChecker/blob/0dfe67fe3e4f83413e747799461bab046ac2f5b4/refchecker/utils.py#L91-L94

**Comment by HuXiangkun** [comment]
Thanks @richardhj for reporting this, I have fixed this issue.
