### ISSUE TITLE
Typo in claude2_extractor.py prompt

### ISSUE THREAD

**Issue by sambayless** [amazon-science/RefChecker#3]
Hi! RefChecker looks really neat! 

I noticed there is a typo in the claude2_extractor prompt:

```
Now geneate the KG for the provided input text:
```

(At line 75, from here https://github.com/amazon-science/RefChecker/blob/main/refchecker/extractor/claude2_extractor.py)

"geneate" should be "generate"

**Comment by sambayless** [comment]
Also, from line 59 in the same file, "occured" should be "occurred":
```
("Announcement of Optimus", "occured at", "Artificial Intelligence (AI) Day event")
```
Both typos are part of the LLM prompt itself, not just typos, so they potentially impact the LLM behaviour.

**Comment by HuXiangkun** [comment]
Thank you for pointing this out, we have corrected them accordingly.
