### ISSUE TITLE
Getting Cuda out of memory error

### ISSUE THREAD

**Issue by isspek** [amazon-science/RefChecker#6]
Hi,

Thanks for the repository. I am running the code on a laptop, so the GPU memory is limited if I use open LLMs (e.g. `extractor = MistralExtractor()`). Is there a way to setup batch size while using these models?

**Comment by HuXiangkun** [comment]
Hi @isspek , the extractors are not using batching for the extraction. The Mistral extractor has 7B parameters, so it is not able to deployed into a laptop, so I think you need a GPU to run the Mistral-based extractor.

**Comment by isspek** [comment]
Thanks for the clarification @HuXiangkun
